# theme: jekyll-theme-cayman
remote_theme: pages-themes/architect@v0.2.0
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/tech.jpg
        height: 640
        width: 1280
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
